In [1]:
from pilco.environments.environment import Environment
import numpy as np

In [2]:
reward_loc = np.array([0., 0.])
reward_scale = np.array([1., 1.])

pendulum = Environment('Pendulum-v0', reward_loc, reward_scale)

In [5]:
state, action, next_state, reward = pendulum.step(np.array([1.]))

In [6]:
state

array([[-0.73700768],
       [-0.75025339]])

In [7]:
action

array([1.])

In [8]:
next_state

array([[-0.79222317],
       [-1.10430976]])

In [9]:
reward

0.6691401677284956